version: '3.8'

services:
  postgres-db:
    image: postgres:13.16
    container_name: pismo-db
    restart: always
    networks:
      - pismo-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=root
      - POSTGRES_USER=pismouser
      - POSTGRES_PASSWORD=pismopass
    volumes:
      # - ./init-db:/docker-entrypoint-initdb.d
      - pismo_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:7.7
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"
    networks:
      - pismo-network
      

volumes:
  pismo_data:

networks:
  pismo-network:
