server:
  port: 8082
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

account:
  api:
    url: http://localhost:8081/accounts/{accountId}

spring:
  application:
    name: service-account
  datasource:
    url: jdbc:postgresql://localhost:5432/transacaodb
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
#    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
